version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "account-mgmt-backend"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1cbhe3g6hqlgb"
s3_prefix = "account-mgmt-backend"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "UserServicesStoreTableName=\"user_services\" RawEventsStoreTableName=\"raw_events\" Environment=\"dev\" VpcStackName=\"vpc-enhanced\" CodeSigningConfigArn=\"none\" PermissionsBoundary=\"none\""
image_repositories = []
